# Generated by Django 5.1.3 on 2024-11-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('residenza', models.CharField(max_length=25)),
                ('nascita', models.DateField(auto_now=True)),
                ('assunzione', models.DateField(auto_now=True)),
                ('ruolo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ubicazione', models.CharField(max_length=50)),
                ('p_iva', models.IntegerField()),
                ('descrizione', models.TextField(max_length=250)),
                ('ut_registrazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AUtente', to='News.utente')),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
            },
        ),
    ]
