# Generated by Django 5.1.3 on 2024-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_utente_assunzione_alter_utente_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='assunzione',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='utente',
            name='nascita',
            field=models.DateField(),
        ),
    ]
