# Generated by Django 5.1.3 on 2024-11-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_utente_assunzione_alter_utente_nascita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_art', models.CharField(max_length=12)),
                ('descrizione', models.CharField(max_length=12)),
                ('qta_sotto_scorta', models.IntegerField()),
                ('qta', models.IntegerField()),
                ('valore_unitario', models.IntegerField()),
                ('ut_registrazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ut_magazzino', to='News.utente')),
            ],
            options={
                'verbose_name': 'Magazzino',
                'verbose_name_plural': 'Magazzini',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta', models.IntegerField()),
                ('data_consegna', models.DateField()),
                ('data_inserimento', models.DateField()),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_ordine', to='News.magazzino')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_ordine', to='News.azienda')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
