# Generated by Django 5.1.3 on 2024-11-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_magazzino_ordine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cognome', models.CharField(max_length=250)),
                ('residenza', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('data_regist', models.DateField(auto_now=True)),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitore',
            },
        ),
        migrations.AddField(
            model_name='magazzino',
            name='Fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FMagazzino', to='News.fornitore'),
        ),
    ]
