# Generated by Django 5.1.3 on 2024-12-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_alter_magazzino_fornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta_ordine', models.IntegerField()),
                ('data_richiesta', models.DateField()),
                ('data_inserimento', models.DateField()),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ARda', to='News.magazzino')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='URda', to='News.utente')),
            ],
            options={
                'verbose_name': 'Rda',
                'verbose_name_plural': 'Rda',
            },
        ),
    ]
